# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DAY10' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DAY10
  pod 'Alamofire'
  pod 'STWebImage'

end
